# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build
        run: |
          git pull origin main
          ./gradlew build -x test
      - name: Test
        run: ./gradlew test -i
      - name: Validate
        run: ./gradlew check
      - name: Analyze sonarqube
        run: |
          ./gradlew dockerComposeUp
          ./gradlew sonarqube -Dsonar.host.url=http://localhost:9000
          ./gradlew -i test jacocoTestReport
      - name: Deploy
        uses: AkhileshNS/heroku-deploy@v3.6.8
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "pet-clinic-app"
          heroku_email: "facundoahumada93@gmail.com"
